// CIBA OS — seed data.
// Partners, programs, and collaborations are REAL (sourced from
// acceleratebusiness.ca and regional press). Team members, ventures, dollar
// amounts, documents, and posts are illustrative dummy data for the demo.

import type {
  ActivityEvent,
  Doc,
  FundingRecord,
  Integration,
  Member,
  Partner,
  Project,
  SocialPost,
  Venture,
} from "./types";

// ---------------- Partners (real organizations) ----------------
export const PARTNERS: Partner[] = [
  {
    id: "tru",
    name: "Thompson Rivers University",
    kind: "university",
    region: "Kamloops, BC",
    about: "CIBA is based on the TRU campus and jointly operates the TRU Generator on-campus accelerator.",
    url: "https://www.tru.ca",
  },
  {
    id: "innovate-bc",
    name: "Innovate BC",
    kind: "government",
    region: "British Columbia",
    about: "Provincial Crown agency; partner on Road to Web Summit Vancouver and AccelerateIP.",
    url: "https://www.innovatebc.ca",
  },
  {
    id: "nvbc",
    name: "New Ventures BC",
    kind: "accelerator",
    region: "British Columbia",
    about: "Co-delivers the AccelerateIP program helping startups protect and leverage IP.",
    url: "https://www.newventuresbc.com",
  },
  {
    id: "accelerate-okanagan",
    name: "Accelerate Okanagan",
    kind: "accelerator",
    region: "Kelowna, BC",
    about: "CIBA is regional delivery partner for AO's PacifiCan-funded ThreeSixty & Delta scale-up programs.",
    url: "https://www.accelerateokanagan.com",
  },
  {
    id: "pacifican",
    name: "PacifiCan",
    kind: "funder",
    region: "Canada (federal)",
    about: "Federal economic development agency for BC; funds the scale-up programs CIBA delivers regionally.",
    url: "https://www.canada.ca/en/pacific-economic-development.html",
  },
  {
    id: "discovery-foundation",
    name: "Discovery Foundation",
    kind: "funder",
    region: "British Columbia",
    about: "Funds the Applied AI Implementation Clinics helping SMEs adopt practical AI.",
  },
  {
    id: "etsi-bc",
    name: "ETSI-BC (Economic Trust of the Southern Interior)",
    kind: "funder",
    region: "Southern Interior, BC",
    about: "Supported CIBA's stakeholder engagement & strategic plan via the Building Economic Capacity stream.",
    url: "https://www.etsi-bc.ca",
  },
  {
    id: "kpmg",
    name: "KPMG",
    kind: "corporate",
    region: "Kamloops, BC",
    about: "Corporate sponsor attracted by CIBA's regional reach and credibility.",
  },
  {
    id: "kis",
    name: "Kamloops Immigration Services",
    kind: "community",
    region: "Kamloops, BC",
    about: "Partner delivering entrepreneurship workshops for new Canadians.",
  },
  {
    id: "scwenwen",
    name: "Sc.wén̓wen (Tk̓emlúps te Secwépemc)",
    kind: "indigenous",
    region: "Tk̓emlúps te Secwépemc",
    about: "Economic development corporation for Tk̓emlúps te Secwépemc; partner on Indigenous business development.",
  },
];

// ---------------- Team members (dummy people, realistic roles) ----------------
export const MEMBERS: Member[] = [
  {
    id: "sachin",
    name: "Sachin Singh",
    title: "Executive Director",
    role: "executive",
    email: "sachin@acceleratebusiness.ca",
    avatarColor: "#0f5c4a",
    projectAccess: "*",
    integrationAccess: "*",
  },
  {
    id: "rob",
    name: "Rob Tremblay",
    title: "Programs Manager",
    role: "programs",
    email: "rob@acceleratebusiness.ca",
    avatarColor: "#2563eb",
    projectAccess: ["tru-generator", "r2wsv", "accelerate-ip", "threesixty-delta"],
    integrationAccess: ["int-drive", "int-crm"],
  },
  {
    id: "sofia",
    name: "Sofia Marques",
    title: "Partnerships & Funding Lead",
    role: "funding",
    email: "sofia@acceleratebusiness.ca",
    avatarColor: "#7c3aed",
    projectAccess: ["threesixty-delta", "ai-clinics", "strategic-plan", "ai-skills"],
    integrationAccess: ["int-quickbooks", "int-drive"],
  },
  {
    id: "jake",
    name: "Jake Williams",
    title: "Marketing & Community Coordinator",
    role: "marketing",
    email: "jake@acceleratebusiness.ca",
    avatarColor: "#e07a2f",
    projectAccess: ["r2wsv", "ai-skills", "ai-clinics"],
    integrationAccess: ["int-buffer", "int-eventbrite", "int-youtube", "int-instagram"],
  },
  {
    id: "anita",
    name: "Anita Baptiste",
    title: "Indigenous & Regional Outreach Advisor",
    role: "outreach",
    email: "anita@acceleratebusiness.ca",
    avatarColor: "#b23b3b",
    projectAccess: ["indigenous-partnership", "newcomer-workshops", "tru-generator"],
    integrationAccess: ["int-drive", "int-crm"],
  },
];

// ---------------- Integrations (mock adapters) ----------------
export const INTEGRATIONS: Integration[] = [
  {
    id: "int-quickbooks",
    name: "Grant & Sponsorship Ledger",
    kind: "financing",
    provider: "QuickBooks Online",
    status: "connected",
    lastSync: "2026-07-01T08:10:00-07:00",
    description: "Tracks grants, sponsorships, and program-delivery funding across every collaboration; feeds the funder-report rollups.",
  },
  {
    id: "int-buffer",
    name: "Social Studio",
    kind: "social",
    provider: "CIBA Studio",
    status: "connected",
    lastSync: "2026-07-01T07:45:00-07:00",
    description: "Create short-form video and publish it to YouTube and Instagram from /os/social — with per-post and channel analytics.",
  },
  {
    id: "int-youtube",
    name: "YouTube Publishing",
    kind: "social",
    provider: "YouTube Data API",
    status: "connected",
    lastSync: "2026-07-01T07:50:00-07:00",
    description: "Direct video uploads (resumable) from the Social Studio, per channel. Powers the Studio's YouTube target.",
  },
  {
    id: "int-instagram",
    name: "Instagram Publishing",
    kind: "social",
    provider: "Instagram Graph API",
    status: "connected",
    lastSync: "2026-07-01T07:50:00-07:00",
    description: "Publishes Reels from the Social Studio via a public media URL, per channel. Powers the Studio's Instagram target.",
  },
  {
    id: "int-eventbrite",
    name: "Event Registrations",
    kind: "social",
    provider: "Eventbrite",
    status: "syncing",
    lastSync: "2026-06-30T22:00:00-07:00",
    description: "Workshop and clinic registrations (Applied AI Clinics, TRU Generator events, newcomer workshops).",
  },
  {
    id: "int-drive",
    name: "Document Vault",
    kind: "data",
    provider: "Google Drive",
    status: "connected",
    lastSync: "2026-07-01T08:30:00-07:00",
    description: "Agreements, funder reports, decks, and budgets — organized per collaboration with sensitivity flags.",
  },
  {
    id: "int-crm",
    name: "Venture & Founder CRM",
    kind: "crm",
    provider: "Airtable",
    status: "attention",
    lastSync: "2026-06-28T16:20:00-07:00",
    description: "Every venture in every program: stage, sector, jobs, revenue — the numbers CIBA reports to funders.",
  },
  {
    id: "int-llm",
    name: "AI Access Layer",
    kind: "llm",
    provider: "Claude (Anthropic)",
    status: "connected",
    lastSync: "2026-07-01T08:35:00-07:00",
    description: "Permission-scoped AI assistant: answers only from data the signed-in member is allowed to see.",
  },
];

// ---------------- Collaborations / projects (real programs) ----------------
export const PROJECTS: Project[] = [
  {
    id: "tru-generator",
    name: "TRU Generator",
    status: "active",
    summary: "On-campus accelerator jointly operated with Thompson Rivers University — mentorship, workshops, and events for students, faculty, staff, and alumni.",
    partnerIds: ["tru"],
    leadMemberId: "rob",
    memberIds: ["rob", "anita", "sachin"],
    integrationIds: ["int-drive", "int-crm", "int-eventbrite"],
    programTag: "TRU Generator",
    start: "2023-09-01",
  },
  {
    id: "r2wsv",
    name: "Road to Web Summit Vancouver",
    status: "active",
    summary: "With Innovate BC: preparing Interior BC startups to showcase at Web Summit Vancouver, incl. the Interior AI Commercialization Sprint (5 sessions, Feb–Apr).",
    partnerIds: ["innovate-bc"],
    leadMemberId: "rob",
    memberIds: ["rob", "jake", "sachin"],
    integrationIds: ["int-buffer", "int-eventbrite", "int-crm"],
    programTag: "R2WSV / AI Commercialization Sprint",
    start: "2026-01-15",
  },
  {
    id: "accelerate-ip",
    name: "AccelerateIP",
    status: "active",
    summary: "With New Ventures BC and Innovate BC: helping Central Interior startups protect, develop, and implement their intellectual property.",
    partnerIds: ["nvbc", "innovate-bc"],
    leadMemberId: "rob",
    memberIds: ["rob", "sachin"],
    integrationIds: ["int-drive", "int-crm"],
    programTag: "AccelerateIP",
    start: "2024-06-01",
  },
  {
    id: "threesixty-delta",
    name: "ThreeSixty & Delta Delivery",
    status: "active",
    summary: "Regional delivery of Accelerate Okanagan's PacifiCan-funded scale-up programs: strategic mentorship, expert advisors, peer networks, co-investment opportunities.",
    partnerIds: ["accelerate-okanagan", "pacifican"],
    leadMemberId: "sofia",
    memberIds: ["sofia", "rob", "sachin"],
    integrationIds: ["int-quickbooks", "int-crm", "int-drive"],
    programTag: "ThreeSixty & Delta",
    start: "2025-04-01",
  },
  {
    id: "ai-clinics",
    name: "Applied AI Implementation Clinics",
    status: "active",
    summary: "Discovery Foundation-funded clinics helping SMEs identify, evaluate, and implement practical AI — summer workshop series Jun–Jul 2026 across HealthTech, CleanTech, GreenTech.",
    partnerIds: ["discovery-foundation"],
    leadMemberId: "sofia",
    memberIds: ["sofia", "jake", "sachin"],
    integrationIds: ["int-quickbooks", "int-eventbrite", "int-buffer", "int-drive"],
    programTag: "Applied AI Clinics",
    start: "2026-05-01",
    end: "2026-08-15",
  },
  {
    id: "ai-skills",
    name: "AI Skills Accelerator",
    status: "active",
    summary: "Hands-on cohort helping regional SMBs adopt AI in day-to-day operations. KPMG sponsors the program.",
    partnerIds: ["kpmg"],
    leadMemberId: "jake",
    memberIds: ["jake", "sofia", "sachin"],
    integrationIds: ["int-buffer", "int-crm", "int-quickbooks"],
    programTag: "AI Skills Accelerator",
    start: "2025-04-15",
  },
  {
    id: "indigenous-partnership",
    name: "Indigenous Business Development",
    status: "active",
    summary: "Partnership with Sc.wén̓wen (Tk̓emlúps te Secwépemc economic development corp): Indigenous business panels at TRU, mentorship agreements with Indigenous-led ventures.",
    partnerIds: ["scwenwen", "tru"],
    leadMemberId: "anita",
    memberIds: ["anita", "sachin"],
    integrationIds: ["int-drive", "int-crm"],
    programTag: "Indigenous Partnership",
    start: "2024-07-01",
  },
  {
    id: "newcomer-workshops",
    name: "Newcomer Entrepreneurship Workshops",
    status: "active",
    summary: "With Kamloops Immigration Services: entrepreneurship workshops for new Canadians building businesses in the region.",
    partnerIds: ["kis"],
    leadMemberId: "anita",
    memberIds: ["anita", "jake", "sachin"],
    integrationIds: ["int-eventbrite", "int-drive"],
    programTag: "Newcomer Workshops",
    start: "2025-09-01",
  },
  {
    id: "strategic-plan",
    name: "Regional Capacity & Strategic Plan",
    status: "wrapped",
    summary: "ETSI-BC-funded (Building Economic Capacity stream): broad stakeholder engagement and the strategic plan behind the Kamloops Innovation → CIBA expansion.",
    partnerIds: ["etsi-bc"],
    leadMemberId: "sachin",
    memberIds: ["sachin", "sofia"],
    integrationIds: ["int-quickbooks", "int-drive"],
    programTag: "Building Economic Capacity",
    start: "2024-01-01",
    end: "2025-03-31",
  },
];

// ---------------- Funding records (dummy amounts, real sources) ----------------
export const FUNDING: FundingRecord[] = [
  {
    id: "f-etsi-1",
    projectId: "strategic-plan",
    source: "ETSI-BC",
    kind: "grant",
    amountCAD: 48000,
    status: "received",
    reportDeadline: "2026-07-15",
    notes: "Building Economic Capacity stream. Final impact report due — draft in Document Vault.",
  },
  {
    id: "f-pacifican-1",
    projectId: "threesixty-delta",
    source: "PacifiCan (via Accelerate Okanagan)",
    kind: "program-delivery",
    amountCAD: 120000,
    status: "committed",
    reportDeadline: "2026-09-30",
    notes: "Regional delivery agreement for ThreeSixty & Delta, FY26 tranche. Quarterly venture metrics required.",
  },
  {
    id: "f-discovery-1",
    projectId: "ai-clinics",
    source: "Discovery Foundation",
    kind: "grant",
    amountCAD: 85000,
    status: "received",
    reportDeadline: "2026-08-31",
    notes: "Applied AI Implementation Clinics — attendance + SME adoption outcomes due post-series.",
  },
  {
    id: "f-kpmg-1",
    projectId: "ai-skills",
    source: "KPMG",
    kind: "sponsorship",
    amountCAD: 25000,
    status: "received",
    notes: "Annual sponsorship of the AI Skills Accelerator. Logo placement + cohort demo-day invite.",
  },
  {
    id: "f-innovatebc-1",
    projectId: "r2wsv",
    source: "Innovate BC",
    kind: "program-delivery",
    amountCAD: 40000,
    status: "received",
    reportDeadline: "2026-07-31",
    notes: "R2WSV delivery — participant outcomes report due end of July.",
  },
  {
    id: "f-nvbc-1",
    projectId: "accelerate-ip",
    source: "New Ventures BC",
    kind: "program-delivery",
    amountCAD: 30000,
    status: "committed",
    notes: "AccelerateIP regional delivery, 2026 intake.",
  },
  {
    id: "f-apply-1",
    projectId: "indigenous-partnership",
    source: "PacifiCan (application)",
    kind: "grant",
    amountCAD: 60000,
    status: "applied",
    notes: "Application submitted for expanded Indigenous entrepreneurship programming. Decision expected Q3 2026.",
  },
];

// ---------------- Social posts (dummy) ----------------
export const SOCIAL: SocialPost[] = [
  {
    id: "s-1",
    projectId: "ai-clinics",
    channel: "LinkedIn",
    status: "published",
    date: "2026-06-24",
    content: "Applied AI Implementation Clinics are live! HealthTech session filled in 48h — CleanTech & GreenTech dates just added. 🧠⚙️",
    engagement: { views: 2140, clicks: 187 },
  },
  {
    id: "s-2",
    projectId: "ai-clinics",
    channel: "Eventbrite",
    status: "scheduled",
    date: "2026-07-08",
    content: "GreenTech AI Clinic — July 15, TRU campus. Bring one real workflow; leave with an implementation plan.",
  },
  {
    id: "s-3",
    projectId: "r2wsv",
    channel: "LinkedIn",
    status: "published",
    date: "2026-05-30",
    content: "Six Interior BC startups walked the floor at Web Summit Vancouver — every one of them came through the Interior AI Commercialization Sprint. Proud is an understatement.",
    engagement: { views: 5320, clicks: 411 },
  },
  {
    id: "s-4",
    projectId: "ai-skills",
    channel: "Instagram",
    status: "draft",
    date: "2026-07-05",
    content: "Cohort 3 applications open — 10 spots for Kamloops-area businesses ready to put AI to work.",
  },
  {
    id: "s-5",
    projectId: "newcomer-workshops",
    channel: "Newsletter",
    status: "scheduled",
    date: "2026-07-10",
    content: "Fall series with Kamloops Immigration Services: business registration, first customers, and funding basics for new Canadians.",
  },
  {
    id: "s-6",
    projectId: "tru-generator",
    channel: "Eventbrite",
    status: "published",
    date: "2026-06-15",
    content: "TRU Generator Summer Pitch Night — students & alumni, 90 seconds each, real feedback panel.",
    engagement: { views: 890, clicks: 203 },
  },
];

// ---------------- Documents (dummy) ----------------
export const DOCS: Doc[] = [
  { id: "d-1", projectId: "strategic-plan", name: "ETSI-BC Final Impact Report (draft)", type: "report", updated: "2026-06-27", owner: "sofia", sensitive: true },
  { id: "d-2", projectId: "strategic-plan", name: "Stakeholder Engagement Summary", type: "report", updated: "2025-02-10", owner: "sachin", sensitive: false },
  { id: "d-3", projectId: "threesixty-delta", name: "AO Regional Delivery Agreement", type: "agreement", updated: "2025-04-02", owner: "sofia", sensitive: true },
  { id: "d-4", projectId: "threesixty-delta", name: "Q2 Venture Metrics for PacifiCan", type: "report", updated: "2026-06-29", owner: "sofia", sensitive: false },
  { id: "d-5", projectId: "ai-clinics", name: "Discovery Foundation Grant Agreement", type: "agreement", updated: "2026-04-20", owner: "sofia", sensitive: true },
  { id: "d-6", projectId: "ai-clinics", name: "Clinic Series Budget", type: "budget", updated: "2026-06-18", owner: "sofia", sensitive: true },
  { id: "d-7", projectId: "ai-clinics", name: "HealthTech Clinic Deck", type: "deck", updated: "2026-06-20", owner: "jake", sensitive: false },
  { id: "d-8", projectId: "r2wsv", name: "Sprint Cohort Outcomes (for Innovate BC)", type: "report", updated: "2026-06-25", owner: "rob", sensitive: false },
  { id: "d-9", projectId: "accelerate-ip", name: "IP Strategy Workshop Materials", type: "deck", updated: "2026-05-12", owner: "rob", sensitive: false },
  { id: "d-10", projectId: "indigenous-partnership", name: "Sc.wén̓wen Partnership MOU", type: "agreement", updated: "2024-08-15", owner: "anita", sensitive: true },
  { id: "d-11", projectId: "indigenous-partnership", name: "PacifiCan Expansion Application", type: "application", updated: "2026-05-30", owner: "anita", sensitive: true },
  { id: "d-12", projectId: "newcomer-workshops", name: "Fall Workshop Series Plan", type: "notes", updated: "2026-06-22", owner: "anita", sensitive: false },
  { id: "d-13", projectId: "tru-generator", name: "TRU Generator Annual Summary", type: "report", updated: "2026-05-01", owner: "rob", sensitive: false },
  { id: "d-14", projectId: "ai-skills", name: "KPMG Sponsorship Agreement", type: "agreement", updated: "2025-04-20", owner: "sachin", sensitive: true },
];

// ---------------- Ventures (dummy companies in real programs) ----------------
export const VENTURES: Venture[] = [
  {
    id: "v-1",
    name: "TrailheadIQ",
    founder: "Jordan Pruden",
    sector: "Tourism SaaS",
    projectIds: ["r2wsv", "threesixty-delta"],
    stage: "growth",
    metrics: { jobs: 4, revenueCAD: 92000, raisedCAD: 150000 },
  },
  {
    id: "v-2",
    name: "Sagebrush Analytics",
    founder: "Dr. Lena Kowalski",
    sector: "AgTech",
    projectIds: ["accelerate-ip", "tru-generator"],
    stage: "validation",
    metrics: { jobs: 2, revenueCAD: 18000, raisedCAD: 0 },
  },
  {
    id: "v-3",
    name: "Cedar Creek Builders",
    founder: "Mike Antoine",
    sector: "Construction",
    projectIds: ["indigenous-partnership"],
    stage: "operating",
    metrics: { jobs: 14, revenueCAD: 1900000, raisedCAD: 0 },
  },
  {
    id: "v-4",
    name: "Nourish Market",
    founder: "Rita Gill",
    sector: "Food Retail",
    projectIds: ["newcomer-workshops", "ai-skills"],
    stage: "operating",
    metrics: { jobs: 6, revenueCAD: 480000, raisedCAD: 0 },
  },
  {
    id: "v-5",
    name: "PulseWear Health",
    founder: "Sam Osei",
    sector: "HealthTech",
    projectIds: ["ai-clinics", "r2wsv"],
    stage: "validation",
    metrics: { jobs: 3, revenueCAD: 0, raisedCAD: 220000 },
  },
  {
    id: "v-6",
    name: "GreenLoop Energy",
    founder: "Tessa Marchand",
    sector: "CleanTech",
    projectIds: ["ai-clinics", "threesixty-delta"],
    stage: "growth",
    metrics: { jobs: 8, revenueCAD: 310000, raisedCAD: 500000 },
  },
];

// ---------------- Activity feed (dummy) ----------------
export const ACTIVITY: ActivityEvent[] = [
  { id: "a-1", when: "2026-07-01T08:32:00-07:00", memberId: "sofia", projectId: "strategic-plan", action: "Updated ETSI-BC final impact report draft" },
  { id: "a-2", when: "2026-06-30T15:10:00-07:00", memberId: "jake", projectId: "ai-clinics", action: "Scheduled GreenTech clinic Eventbrite listing" },
  { id: "a-3", when: "2026-06-30T11:05:00-07:00", memberId: "rob", projectId: "r2wsv", action: "Submitted Sprint cohort outcomes to Innovate BC portal" },
  { id: "a-4", when: "2026-06-29T09:40:00-07:00", memberId: "sofia", projectId: "threesixty-delta", action: "Exported Q2 venture metrics for PacifiCan report" },
  { id: "a-5", when: "2026-06-28T14:00:00-07:00", memberId: "anita", projectId: "indigenous-partnership", action: "Logged mentorship session with Cedar Creek Builders" },
  { id: "a-6", when: "2026-06-27T10:15:00-07:00", memberId: "sachin", action: "Reviewed FY27 budget scenarios with the board" },
  { id: "a-7", when: "2026-06-26T16:45:00-07:00", memberId: "jake", projectId: "ai-skills", action: "Drafted Cohort 3 application announcement" },
  { id: "a-8", when: "2026-06-25T13:20:00-07:00", memberId: "anita", projectId: "newcomer-workshops", action: "Confirmed fall series dates with Kamloops Immigration Services" },
];
